INSERT INTO vestuarios (nombre, sexo) VALUES ('A', 'M');
INSERT INTO vestuarios (nombre, sexo) VALUES ('B', 'F');
INSERT INTO vestuarios (nombre, sexo) VALUES ('C', 'M');
INSERT INTO vestuarios (nombre, sexo) VALUES ('D', 'F');
INSERT INTO vestuarios (nombre, sexo) VALUES ('E', 'M');
INSERT INTO vestuarios (nombre, sexo) VALUES ('F', 'F');
INSERT INTO vestuarios (nombre, sexo) VALUES ('G', 'M');
INSERT INTO vestuarios (nombre, sexo) VALUES ('H', 'F');
INSERT INTO vestuarios (nombre, sexo) VALUES ('I', 'M');
INSERT INTO vestuarios (nombre, sexo) VALUES ('J', 'F');

-- Inserts para el vestuario A (Masculino)
INSERT INTO taquillas (vestuario_id, codigo_taquilla, nombre_apellidos, categoria_profesional, servicio, telefono, empresa_externa) VALUES
(1, 'A01', 'Juan Pérez', 'Auxiliar de Enfermería', 'Enfermería', NULL, false),
(1, 'A02', 'Pedro Gómez', 'Médico Especialista', 'Urgencias', NULL, false),
(1, 'A03', 'Carlos López', 'Cirujano', 'Cirugía', NULL, false),
(1, 'A04', 'Luis Martínez', 'Técnico de Radiología', 'Radiología', NULL, false),
(1, 'A05', 'José Fernández', 'Farmacéutico', 'Farmacia', NULL, false),
(1, 'A06', 'Miguel Sánchez', 'Anestesista', 'Anestesiología', NULL, false),
(1, 'A07', 'Andrés García', 'Médico General', 'Medicina General', NULL, false),
(1, 'A08', 'Javier Jiménez', 'Enfermero', 'Enfermería', NULL, false),
(1, 'A09', 'Daniel Rodríguez', 'Cardiólogo', 'Cardiología', NULL, false),
(1, 'A10', 'Fernando Hernández', 'Neurólogo', 'Neurología', NULL, false),
(1, 'A11', 'Raúl Ruiz', 'Psiquiatra', 'Psiquiatría', NULL, false),
(1, 'A12', 'Sergio Ramírez', 'Geriatra', 'Geriatría', NULL, false),
(1, 'A13', 'Adrián Morales', 'Dermatólogo', 'Dermatología', NULL, false),
(1, 'A14', 'Alejandro Ortiz', 'Gastroenterólogo', 'Gastroenterología', NULL, false),
(1, 'A15', 'Rubén Torres', 'Nefrólogo', 'Nefrología', NULL, false),
(1, 'A16', 'Manuel Domínguez', 'Neumólogo', 'Neumología', NULL, false),
(1, 'A17', 'Hugo Delgado', 'Oncólogo', 'Oncología', NULL, false),
(1, 'A18', 'Iván Castillo', 'Oftalmólogo', 'Oftalmología', NULL, false),
(1, 'A19', 'Mario Gil', 'Otorrinolaringólogo', 'Otorrinolaringología', NULL, false),
(1, 'A20', 'Pablo Rivas', 'Traumatólogo', 'Traumatología', NULL, false),
(1, 'A21', 'Diego Vázquez', 'Urólogo', 'Urología', NULL, false),
(1, 'A22', 'Francisco Soto', 'Endocrinólogo', 'Endocrinología', NULL, false),
(1, 'A23', 'Víctor Guerrero', 'Hematólogo', 'Hematología', NULL, false),
(1, 'A24', 'Tomás Moya', 'Reumatólogo', 'Reumatología', NULL, false),
(1, 'A25', 'Jorge Peña', 'Rehabilitador', 'Rehabilitación', NULL, false),
(1, 'A26', 'Álvaro Pardo', 'Médico Internista', 'Medicina Interna', NULL, false),
(1, 'A27', 'David León', 'Ginecólogo', 'Ginecología', NULL, false),
(1, 'A28', 'Cristian Muñoz', 'Pediatra', 'Pediatría', NULL, false),
(1, 'A29', 'Santiago Mendoza', 'Inmunólogo', 'Inmunología', NULL, false),
(1, 'A30', 'Óscar Herrera', 'Microbiólogo', 'Microbiología', NULL, false),
(1, 'A31', 'Sebastián Flores', 'Epidemiólogo', 'Epidemiología', NULL, false),
(1, 'A32', 'Vicente Cabrera', 'Nutricionista', 'Nutrición', NULL, false),
(1, 'A33', 'Lucas Medina', 'Fisioterapeuta', 'Fisioterapia', NULL, false),
(1, 'A34', 'Antonio Escobar', 'Podólogo', 'Podología', NULL, false),
(1, 'A35', 'Jesús Campos', 'Técnico de Laboratorio', 'Laboratorio', NULL, false),
(1, 'A36', 'Joaquín Reyes', 'Enfermero', 'Urgencias', NULL, false),
(1, 'A37', 'Alberto Soto', 'Técnico de Mantenimiento', 'Mantenimiento', '600123456', true),
(1, 'A38', 'Ricardo Núñez', 'Técnico de Limpieza', 'Limpieza', '600654321', true),
(1, 'A39', 'Martín Díaz', 'Seguridad', 'Seguridad', '600987654', true),
(1, 'A40', 'Mario Ruiz', 'Jardinero', 'Jardinería', '600456789', true),
(1, 'A41', 'José Miguel Ortega', 'Técnico de Ascensores', 'Mantenimiento', '600321987', true),
(1, 'A42', 'Gabriel Ramos', 'Técnico de Climatización', 'Mantenimiento', '600654789', true),
(1, 'A43', 'Enrique Morales', 'Electricista', 'Mantenimiento', '600321654', true),
(1, 'A44', 'Miguel Ángel Martín', 'Plomero', 'Mantenimiento', '600987321', true),
(1, 'A45', 'Felipe Navarro', 'Carpintero', 'Mantenimiento', '600654987', true),
(1, 'A46', 'Rubén Santos', 'Pintor', 'Mantenimiento', '600123789', true),
(1, 'A47', 'Francisco Lozano', 'Conserje', 'Conserjería', '600456321', true),
(1, 'A48', 'Eduardo Iglesias', 'Portero', 'Portería', '600789123', true),
(1, 'A49', 'Víctor Prieto', 'Ayudante de Cocina', 'Cocina', '600321123', true),
(1, 'A50', 'Luis Blanco', 'Técnico de Fontanería', 'Fontanería', '600654123', true);

-- Inserts para el vestuario B (Femenino)
INSERT INTO taquillas (vestuario_id, codigo_taquilla, nombre_apellidos, categoria_profesional, servicio, telefono, empresa_externa) VALUES
(2, 'B01', 'Ana Gómez', 'Auxiliar de Enfermería', 'Enfermería', NULL, false),
(2, 'B02', 'María López', 'Médico Especialista', 'Urgencias', NULL, false),
(2, 'B03', 'Laura Martínez', 'Cirujana', 'Cirugía', NULL, false),
(2, 'B04', 'Carmen Rodríguez', 'Técnica de Radiología', 'Radiología', NULL, false),
(2, 'B05', 'Lucía Hernández', 'Farmacéutica', 'Farmacia', NULL, false),
(2, 'B06', 'Elena Sánchez', 'Anestesista', 'Anestesiología', NULL, false),
(2, 'B07', 'Isabel García', 'Médica General', 'Medicina General', NULL, false),
(2, 'B08', 'Patricia Jiménez', 'Enfermera', 'Enfermería', NULL, false),
(2, 'B09', 'Sara Rodríguez', 'Cardióloga', 'Cardiología', NULL, false),
(2, 'B10', 'Nuria Hernández', 'Neuróloga', 'Neurología', NULL, false),
(2, 'B11', 'Sandra Ruiz', 'Psiquiatra', 'Psiquiatría', NULL, false),
(2, 'B12', 'Adriana Ramírez', 'Geriatra', 'Geriatría', NULL, false),
(2, 'B13', 'Sofía Morales', 'Dermatóloga', 'Dermatología', NULL, false),
(2, 'B14', 'Clara Ortiz', 'Gastroenteróloga', 'Gastroenterología', NULL, false),
(2, 'B15', 'Marta Torres', 'Nefróloga', 'Nefrología', NULL, false),
(2, 'B16', 'Rosa Domínguez', 'Neumóloga', 'Neumología', NULL, false),
(2, 'B17', 'Natalia Delgado', 'Oncóloga', 'Oncología', NULL, false),
(2, 'B18', 'Paula Castillo', 'Oftalmóloga', 'Oftalmología', NULL, false),
(2, 'B19', 'Gloria Gil', 'Otorrinolaringóloga', 'Otorrinolaringología', NULL, false),
(2, 'B20', 'Celia Rivas', 'Traumatóloga', 'Traumatología', NULL, false),
(2, 'B21', 'Ángela Vázquez', 'Uróloga', 'Urología', NULL, false),
(2, 'B22', 'Olga Soto', 'Endocrinóloga', 'Endocrinología', NULL, false),
(2, 'B23', 'Verónica Guerrero', 'Hematóloga', 'Hematología', NULL, false),
(2, 'B24', 'Beatriz Moya', 'Reumatóloga', 'Reumatología', NULL, false),
(2, 'B25', 'Alejandra Peña', 'Rehabilitadora', 'Rehabilitación', NULL, false),
(2, 'B26', 'Cristina Pardo', 'Médica Internista', 'Medicina Interna', NULL, false),
(2, 'B27', 'Mercedes León', 'Ginecóloga', 'Ginecología', NULL, false),
(2, 'B28', 'Inés Muñoz', 'Pediatra', 'Pediatría', NULL, false),
(2, 'B29', 'Eva Mendoza', 'Inmunóloga', 'Inmunología', NULL, false),
(2, 'B30', 'Silvia Herrera', 'Microbióloga', 'Microbiología', NULL, false),
(2, 'B31', 'Patricia Flores', 'Epidemióloga', 'Epidemiología', NULL, false),
(2, 'B32', 'Carolina Cabrera', 'Nutricionista', 'Nutrición', NULL, false),
(2, 'B33', 'Mónica Medina', 'Fisioterapeuta', 'Fisioterapia', NULL, false),
(2, 'B34', 'Marta Escobar', 'Podóloga', 'Podología', NULL, false),
(2, 'B35', 'Lorena Campos', 'Técnica de Laboratorio', 'Laboratorio', NULL, false),
(2, 'B36', 'Vanessa Reyes', 'Enfermera', 'Urgencias', NULL, false),
(2, 'B37', 'Raquel Soto', 'Técnica de Mantenimiento', 'Mantenimiento', '600123456', true),
(2, 'B38', 'Pilar Núñez', 'Técnica de Limpieza', 'Limpieza', '600654321', true),
(2, 'B39', 'Elisa Díaz', 'Seguridad', 'Seguridad', '600987654', true),
(2, 'B40', 'Mercedes Ruiz', 'Jardinera', 'Jardinería', '600456789', true),
(2, 'B41', 'Teresa Ortega', 'Técnica de Ascensores', 'Mantenimiento', '600321987', true),
(2, 'B42', 'María Ramos', 'Técnica de Climatización', 'Mantenimiento', '600654789', true),
(2, 'B43', 'Carmen Morales', 'Electricista', 'Mantenimiento', '600321654', true),
(2, 'B44', 'Beatriz Martín', 'Plomera', 'Mantenimiento', '600987321', true),
(2, 'B45', 'Rosa Navarro', 'Carpintera', 'Mantenimiento', '600654987', true),
(2, 'B46', 'Ana Santos', 'Pintora', 'Mantenimiento', '600123789', true),
(2, 'B47', 'Laura Lozano', 'Conserje', 'Conserjería', '600456321', true),
(2, 'B48', 'Susana Iglesias', 'Portera', 'Portería', '600789123', true),
(2, 'B49', 'Paz Prieto', 'Ayudante de Cocina', 'Cocina', '600321123', true),
(2, 'B50', 'Diana Blanco', 'Técnica de Fontanería', 'Fontanería', '600654123', true);

-- Inserts para el vestuario C (Masculino)
INSERT INTO taquillas (vestuario_id, codigo_taquilla, nombre_apellidos, categoria_profesional, servicio, telefono, empresa_externa) VALUES
(3, 'C01', 'Carlos López', 'Auxiliar de Enfermería', 'Enfermería', NULL, false),
(3, 'C02', 'Miguel Rodríguez', 'Médico Especialista', 'Urgencias', NULL, false),
(3, 'C03', 'Pedro Martínez', 'Cirujano', 'Cirugía', NULL, false),
(3, 'C04', 'Juan Sánchez', 'Técnico de Radiología', 'Radiología', NULL, false),
(3, 'C05', 'Luis Hernández', 'Farmacéutico', 'Farmacia', NULL, false),
(3, 'C06', 'José García', 'Anestesista', 'Anestesiología', NULL, false),
(3, 'C07', 'David Jiménez', 'Médico General', 'Medicina General', NULL, false),
(3, 'C08', 'Javier Ruiz', 'Enfermero', 'Enfermería', NULL, false),
(3, 'C09', 'Fernando Ramírez', 'Cardiólogo', 'Cardiología', NULL, false),
(3, 'C10', 'Ricardo Morales', 'Neurólogo', 'Neurología', NULL, false),
(3, 'C11', 'Ángel Díaz', 'Psiquiatra', 'Psiquiatría', NULL, false),
(3, 'C12', 'Eduardo Romero', 'Geriatra', 'Geriatría', NULL, false),
(3, 'C13', 'Vicente Gil', 'Dermatólogo', 'Dermatología', NULL, false),
(3, 'C14', 'Adrián Ortiz', 'Gastroenterólogo', 'Gastroenterología', NULL, false),
(3, 'C15', 'Sergio Torres', 'Nefrólogo', 'Nefrología', NULL, false),
(3, 'C16', 'Pablo Domínguez', 'Neumólogo', 'Neumología', NULL, false),
(3, 'C17', 'Rafael Delgado', 'Oncólogo', 'Oncología', NULL, false),
(3, 'C18', 'Daniel Castillo', 'Oftalmólogo', 'Oftalmología', NULL, false),
(3, 'C19', 'Mario Rivas', 'Otorrinolaringólogo', 'Otorrinolaringología', NULL, false),
(3, 'C20', 'Iván Vázquez', 'Traumatólogo', 'Traumatología', NULL, false),
(3, 'C21', 'Raúl Soto', 'Urólogo', 'Urología', NULL, false),
(3, 'C22', 'Gonzalo Guerrero', 'Endocrinólogo', 'Endocrinología', NULL, false),
(3, 'C23', 'Alberto Moya', 'Hematólogo', 'Hematología', NULL, false),
(3, 'C24', 'Diego Peña', 'Reumatólogo', 'Reumatología', NULL, false),
(3, 'C25', 'Francisco Pardo', 'Rehabilitador', 'Rehabilitación', NULL, false),
(3, 'C26', 'Alejandro León', 'Médico Internista', 'Medicina Interna', NULL, false),
(3, 'C27', 'Marcos Muñoz', 'Ginecólogo', 'Ginecología', NULL, false),
(3, 'C28', 'Héctor Mendoza', 'Pediatra', 'Pediatría', NULL, false),
(3, 'C29', 'Rodrigo Herrera', 'Inmunólogo', 'Inmunología', NULL, false),
(3, 'C30', 'Gabriel Flores', 'Microbiólogo', 'Microbiología', NULL, false),
(3, 'C31', 'Samuel Cabrera', 'Epidemiólogo', 'Epidemiología', NULL, false),
(3, 'C32', 'Rubén Medina', 'Nutricionista', 'Nutrición', NULL, false),
(3, 'C33', 'Manuel Escobar', 'Fisioterapeuta', 'Fisioterapia', NULL, false),
(3, 'C34', 'Hugo Campos', 'Podólogo', 'Podología', NULL, false),
(3, 'C35', 'Víctor Reyes', 'Técnico de Laboratorio', 'Laboratorio', NULL, false),
(3, 'C36', 'Adrián Soto', 'Enfermero', 'Urgencias', NULL, false),
(3, 'C37', 'Andrés Núñez', 'Técnico de Mantenimiento', 'Mantenimiento', '600123456', true),
(3, 'C38', 'Álvaro Díaz', 'Técnico de Limpieza', 'Limpieza', '600654321', true),
(3, 'C39', 'Julio Martín', 'Seguridad', 'Seguridad', '600987654', true),
(3, 'C40', 'Oscar Ramos', 'Jardinero', 'Jardinería', '600456789', true),
(3, 'C41', 'Antonio Morales', 'Técnico de Ascensores', 'Mantenimiento', '600321987', true),
(3, 'C42', 'Félix García', 'Técnico de Climatización', 'Mantenimiento', '600654789', true),
(3, 'C43', 'Marcelo Sánchez', 'Electricista', 'Mantenimiento', '600321654', true),
(3, 'C44', 'Roberto Ruiz', 'Plomero', 'Mantenimiento', '600987321', true),
(3, 'C45', 'Tomás Navarro', 'Carpintero', 'Mantenimiento', '600654987', true),
(3, 'C46', 'Cristian Santos', 'Pintor', 'Mantenimiento', '600123789', true),
(3, 'C47', 'Ramón Lozano', 'Conserje', 'Conserjería', '600456321', true),
(3, 'C48', 'Felipe Iglesias', 'Portero', 'Portería', '600789123', true),
(3, 'C49', 'Hernán Prieto', 'Ayudante de Cocina', 'Cocina', '600321123', true),
(3, 'C50', 'Esteban Blanco', 'Técnico de Fontanería', 'Fontanería', '600654123', true);

-- Inserts para el vestuario D (Femenino)
INSERT INTO taquillas (vestuario_id, codigo_taquilla, nombre_apellidos, categoria_profesional, servicio, telefono, empresa_externa) VALUES
(4, 'D01', 'Alicia Gómez', 'Auxiliar de Enfermería', 'Enfermería', NULL, false),
(4, 'D02', 'Blanca López', 'Médico Especialista', 'Urgencias', NULL, false),
(4, 'D03', 'Clara Martínez', 'Cirujana', 'Cirugía', NULL, false),
(4, 'D04', 'Daniela Rodríguez', 'Técnica de Radiología', 'Radiología', NULL, false),
(4, 'D05', 'Elena Hernández', 'Farmacéutica', 'Farmacia', NULL, false),
(4, 'D06', 'Fernanda Sánchez', 'Anestesista', 'Anestesiología', NULL, false),
(4, 'D07', 'Gabriela García', 'Médica General', 'Medicina General', NULL, false),
(4, 'D08', 'Hilda Jiménez', 'Enfermera', 'Enfermería', NULL, false),
(4, 'D09', 'Inés Ramírez', 'Cardióloga', 'Cardiología', NULL, false),
(4, 'D10', 'Juana Morales', 'Neuróloga', 'Neurología', NULL, false),
(4, 'D11', 'Karla Ruiz', 'Psiquiatra', 'Psiquiatría', NULL, false),
(4, 'D12', 'Laura Romero', 'Geriatra', 'Geriatría', NULL, false),
(4, 'D13', 'Marta Gil', 'Dermatóloga', 'Dermatología', NULL, false),
(4, 'D14', 'Natalia Ortiz', 'Gastroenteróloga', 'Gastroenterología', NULL, false),
(4, 'D15', 'Olga Torres', 'Nefróloga', 'Nefrología', NULL, false),
(4, 'D16', 'Patricia Domínguez', 'Neumóloga', 'Neumología', NULL, false),
(4, 'D17', 'Raquel Delgado', 'Oncóloga', 'Oncología', NULL, false),
(4, 'D18', 'Sara Castillo', 'Oftalmóloga', 'Oftalmología', NULL, false),
(4, 'D19', 'Teresa Rivas', 'Otorrinolaringóloga', 'Otorrinolaringología', NULL, false),
(4, 'D20', 'Ursula Vázquez', 'Traumatóloga', 'Traumatología', NULL, false),
(4, 'D21', 'Verónica Soto', 'Uróloga', 'Urología', NULL, false),
(4, 'D22', 'Wendy Guerrero', 'Endocrinóloga', 'Endocrinología', NULL, false),
(4, 'D23', 'Ximena Moya', 'Hematóloga', 'Hematología', NULL, false),
(4, 'D24', 'Yolanda Peña', 'Reumatóloga', 'Reumatología', NULL, false),
(4, 'D25', 'Zaira Pardo', 'Rehabilitadora', 'Rehabilitación', NULL, false),
(4, 'D26', 'Adela León', 'Médica Internista', 'Medicina Interna', NULL, false),
(4, 'D27', 'Beatriz Muñoz', 'Ginecóloga', 'Ginecología', NULL, false),
(4, 'D28', 'Claudia Mendoza', 'Pediatra', 'Pediatría', NULL, false),
(4, 'D29', 'Dolores Herrera', 'Inmunóloga', 'Inmunología', NULL, false),
(4, 'D30', 'Eva Flores', 'Microbióloga', 'Microbiología', NULL, false),
(4, 'D31', 'Fátima Cabrera', 'Epidemióloga', 'Epidemiología', NULL, false),
(4, 'D32', 'Gloria Medina', 'Nutricionista', 'Nutrición', NULL, false),
(4, 'D33', 'Hilda Escobar', 'Fisioterapeuta', 'Fisioterapia', NULL, false),
(4, 'D34', 'Irene Campos', 'Podóloga', 'Podología', NULL, false),
(4, 'D35', 'Jessica Reyes', 'Técnica de Laboratorio', 'Laboratorio', NULL, false),
(4, 'D36', 'Karen Soto', 'Enfermera', 'Urgencias', NULL, false),
(4, 'D37', 'Liliana Núñez', 'Técnica de Mantenimiento', 'Mantenimiento', '600123456', true),
(4, 'D38', 'Marina Díaz', 'Técnica de Limpieza', 'Limpieza', '600654321', true),
(4, 'D39', 'Nadia Martín', 'Seguridad', 'Seguridad', '600987654', true),
(4, 'D40', 'Olga Ramos', 'Jardinera', 'Jardinería', '600456789', true),
(4, 'D41', 'Paula Morales', 'Técnica de Ascensores', 'Mantenimiento', '600321987', true),
(4, 'D42', 'Rocío García', 'Técnica de Climatización', 'Mantenimiento', '600654789', true),
(4, 'D43', 'Sonia Sánchez', 'Electricista', 'Mantenimiento', '600321654', true),
(4, 'D44', 'Tatiana Ruiz', 'Plomera', 'Mantenimiento', '600987321', true),
(4, 'D45', 'Ursula Navarro', 'Carpintera', 'Mantenimiento', '600654987', true),
(4, 'D46', 'Verónica Santos', 'Pintora', 'Mantenimiento', '600123789', true),
(4, 'D47', 'Wendy Lozano', 'Conserje', 'Conserjería', '600456321', true),
(4, 'D48', 'Ximena Iglesias', 'Portera', 'Portería', '600789123', true),
(4, 'D49', 'Yolanda Prieto', 'Ayudante de Cocina', 'Cocina', '600321123', true),
(4, 'D50', 'Zaira Blanco', 'Técnica de Fontanería', 'Fontanería', '600654123', true);
