INSERT INTO vestuarios (nombre, sexo) VALUES ('A', 'M');
INSERT INTO vestuarios (nombre, sexo) VALUES ('B', 'F');
INSERT INTO vestuarios (nombre, sexo) VALUES ('C', 'M');
INSERT INTO vestuarios (nombre, sexo) VALUES ('D', 'F');
INSERT INTO vestuarios (nombre, sexo) VALUES ('E', 'M');
INSERT INTO vestuarios (nombre, sexo) VALUES ('F', 'F');
INSERT INTO vestuarios (nombre, sexo) VALUES ('G', 'M');
INSERT INTO vestuarios (nombre, sexo) VALUES ('H', 'F');
INSERT INTO vestuarios (nombre, sexo) VALUES ('I', 'M');
INSERT INTO vestuarios (nombre, sexo) VALUES ('J', 'F');

-- Inserts para el vestuario A (Masculino)
INSERT INTO taquillas (vestuario_id, codigo_taquilla, nombre_apellidos, categoria_profesional, servicio, telefono, empresa_externa, fecha_revision, revisado) VALUES
(1, 'A01', 'Juan Pérez', 'Auxiliar de Enfermería', 'Enfermería', NULL, false, NULL, false),
(1, 'A02', 'Pedro Gómez', 'Médico Especialista', 'Urgencias', NULL, false, NULL, false),
(1, 'A03', 'Carlos López', 'Cirujano', 'Cirugía', NULL, false, NULL, false),
(1, 'A04', 'Luis Martínez', 'Técnico de Radiología', 'Radiología', NULL, false, NULL, false),
(1, 'A05', 'José Fernández', 'Farmacéutico', 'Farmacia', NULL, false, NULL, false),
(1, 'A06', 'Miguel Sánchez', 'Anestesista', 'Anestesiología', NULL, false, NULL, false),
(1, 'A07', 'Andrés García', 'Médico General', 'Medicina General', NULL, false, NULL, false),
(1, 'A08', 'Javier Jiménez', 'Enfermero', 'Enfermería', NULL, false, NULL, false),
(1, 'A09', 'Daniel Rodríguez', 'Cardiólogo', 'Cardiología', NULL, false, NULL, false),
(1, 'A10', 'Fernando Hernández', 'Neurólogo', 'Neurología', NULL, false, NULL, false),
(1, 'A11', 'Raúl Ruiz', 'Psiquiatra', 'Psiquiatría', NULL, false, NULL, false),
(1, 'A12', 'Sergio Ramírez', 'Geriatra', 'Geriatría', NULL, false, NULL, false),
(1, 'A13', 'Adrián Morales', 'Dermatólogo', 'Dermatología', NULL, false, NULL, false),
(1, 'A14', 'Alejandro Ortiz', 'Gastroenterólogo', 'Gastroenterología', NULL, false, NULL, false),
(1, 'A15', 'Rubén Torres', 'Nefrólogo', 'Nefrología', NULL, false, NULL, false),
(1, 'A16', 'Manuel Domínguez', 'Neumólogo', 'Neumología', NULL, false, NULL, false),
(1, 'A17', 'Hugo Delgado', 'Oncólogo', 'Oncología', NULL, false, NULL, false),
(1, 'A18', 'Iván Castillo', 'Oftalmólogo', 'Oftalmología', NULL, false, NULL, false),
(1, 'A19', 'Mario Gil', 'Otorrinolaringólogo', 'Otorrinolaringología', NULL, false, NULL, false),
(1, 'A20', 'Pablo Rivas', 'Traumatólogo', 'Traumatología', NULL, false, NULL, false),
(1, 'A21', 'Diego Vázquez', 'Urólogo', 'Urología', NULL, false, NULL, false),
(1, 'A22', 'Francisco Soto', 'Endocrinólogo', 'Endocrinología', NULL, false, NULL, false),
(1, 'A23', 'Víctor Guerrero', 'Hematólogo', 'Hematología', NULL, false, NULL, false),
(1, 'A24', 'Tomás Moya', 'Reumatólogo', 'Reumatología', NULL, false, NULL, false),
(1, 'A25', 'Jorge Peña', 'Rehabilitador', 'Rehabilitación', NULL, false, NULL, false),
(1, 'A26', 'Álvaro Pardo', 'Médico Internista', 'Medicina Interna', NULL, false, NULL, false),
(1, 'A27', 'David León', 'Ginecólogo', 'Ginecología', NULL, false, NULL, false),
(1, 'A28', 'Cristian Muñoz', 'Pediatra', 'Pediatría', NULL, false, NULL, false),
(1, 'A29', 'Santiago Mendoza', 'Inmunólogo', 'Inmunología', NULL, false, NULL, false),
(1, 'A30', 'Óscar Herrera', 'Microbiólogo', 'Microbiología', NULL, false, NULL, false),
(1, 'A31', 'Sebastián Flores', 'Epidemiólogo', 'Epidemiología', NULL, false, NULL, false),
(1, 'A32', 'Vicente Cabrera', 'Nutricionista', 'Nutrición', NULL, false, NULL, false),
(1, 'A33', 'Lucas Medina', 'Fisioterapeuta', 'Fisioterapia', NULL, false, NULL, false),
(1, 'A34', 'Antonio Escobar', 'Podólogo', 'Podología', NULL, false, NULL, false),
(1, 'A35', 'Jesús Campos', 'Técnico de Laboratorio', 'Laboratorio', NULL, false, NULL, false),
(1, 'A36', 'Joaquín Reyes', 'Enfermero', 'Urgencias', NULL, false, NULL, false),
(1, 'A37', 'Alberto Soto', 'Técnico de Mantenimiento', 'Mantenimiento', '600123456', true, NULL, false),
(1, 'A38', 'Ricardo Núñez', 'Técnico de Limpieza', 'Limpieza', '600654321', true, NULL, false),
(1, 'A39', 'Martín Díaz', 'Seguridad', 'Seguridad', '600987654', true, NULL, false),
(1, 'A40', 'Mario Ruiz', 'Jardinero', 'Jardinería', '600456789', true, NULL, false),
(1, 'A41', 'José Miguel Ortega', 'Técnico de Ascensores', 'Mantenimiento', '600321987', true, NULL, false),
(1, 'A42', 'Gabriel Ramos', 'Técnico de Climatización', 'Mantenimiento', '600654789', true, NULL, false),
(1, 'A43', 'Enrique Morales', 'Electricista', 'Mantenimiento', '600321654', true, NULL, false),
(1, 'A44', 'Miguel Ángel Martín', 'Plomero', 'Mantenimiento', '600987321', true, NULL, false),
(1, 'A45', 'Felipe Navarro', 'Carpintero', 'Mantenimiento', '600654987', true, NULL, false),
(1, 'A46', 'Rubén Santos', 'Pintor', 'Mantenimiento', '600123789', true, NULL, false),
(1, 'A47', 'Francisco Lozano', 'Conserje', 'Conserjería', '600456321', true, NULL, false),
(1, 'A48', 'Eduardo Iglesias', 'Portero', 'Portería', '600789123', true, NULL, false),
(1, 'A49', 'Víctor Prieto', 'Ayudante de Cocina', 'Cocina', '600321123', true, NULL, false),
(1, 'A50', 'Luis Blanco', 'Técnico de Fontanería', 'Fontanería', '600654123', true, NULL, false);


-- Inserts para el vestuario B (Femenino)
INSERT INTO taquillas (vestuario_id, codigo_taquilla, nombre_apellidos, categoria_profesional, servicio, telefono, empresa_externa, fecha_revision, revisado) VALUES
(2, 'B01', 'Ana Gómez', 'Auxiliar de Enfermería', 'Enfermería', NULL, false, NULL, false),
(2, 'B02', 'María López', 'Médico Especialista', 'Urgencias', NULL, false, NULL, false),
(2, 'B03', 'Laura Martínez', 'Cirujana', 'Cirugía', NULL, false, NULL, false),
(2, 'B04', 'Carmen Rodríguez', 'Técnica de Radiología', 'Radiología', NULL, false, NULL, false),
(2, 'B05', 'Lucía Hernández', 'Farmacéutica', 'Farmacia', NULL, false, NULL, false),
(2, 'B06', 'Elena Sánchez', 'Anestesista', 'Anestesiología', NULL, false, NULL, false),
(2, 'B07', 'Isabel García', 'Médica General', 'Medicina General', NULL, false, NULL, false),
(2, 'B08', 'Patricia Jiménez', 'Enfermera', 'Enfermería', NULL, false, NULL, false),
(2, 'B09', 'Sara Rodríguez', 'Cardióloga', 'Cardiología', NULL, false, NULL, false),
(2, 'B10', 'Nuria Hernández', 'Neuróloga', 'Neurología', NULL, false, NULL, false),
(2, 'B11', 'Sandra Ruiz', 'Psiquiatra', 'Psiquiatría', NULL, false, NULL, false),
(2, 'B12', 'Adriana Ramírez', 'Geriatra', 'Geriatría', NULL, false, NULL, false),
(2, 'B13', 'Sofía Morales', 'Dermatóloga', 'Dermatología', NULL, false, NULL, false),
(2, 'B14', 'Clara Ortiz', 'Gastroenteróloga', 'Gastroenterología', NULL, false, NULL, false),
(2, 'B15', 'Marta Torres', 'Nefróloga', 'Nefrología', NULL, false, NULL, false),
(2, 'B16', 'Rosa Domínguez', 'Neumóloga', 'Neumología', NULL, false, NULL, false),
(2, 'B17', 'Natalia Delgado', 'Oncóloga', 'Oncología', NULL, false, NULL, false),
(2, 'B18', 'Paula Castillo', 'Oftalmóloga', 'Oftalmología', NULL, false, NULL, false),
(2, 'B19', 'Gloria Gil', 'Otorrinolaringóloga', 'Otorrinolaringología', NULL, false, NULL, false),
(2, 'B20', 'Celia Rivas', 'Traumatóloga', 'Traumatología', NULL, false, NULL, false),
(2, 'B21', 'Ángela Vázquez', 'Uróloga', 'Urología', NULL, false, NULL, false),
(2, 'B22', 'Olga Soto', 'Endocrinóloga', 'Endocrinología', NULL, false, NULL, false),
(2, 'B23', 'Verónica Guerrero', 'Hematóloga', 'Hematología', NULL, false, NULL, false),
(2, 'B24', 'Beatriz Moya', 'Reumatóloga', 'Reumatología', NULL, false, NULL, false),
(2, 'B25', 'Alejandra Peña', 'Rehabilitadora', 'Rehabilitación', NULL, false, NULL, false),
(2, 'B26', 'Cristina Pardo', 'Médica Internista', 'Medicina Interna', NULL, false, NULL, false),
(2, 'B27', 'Mercedes León', 'Ginecóloga', 'Ginecología', NULL, false, NULL, false),
(2, 'B28', 'Inés Muñoz', 'Pediatra', 'Pediatría', NULL, false, NULL, false),
(2, 'B29', 'Eva Mendoza', 'Inmunóloga', 'Inmunología', NULL, false, NULL, false),
(2, 'B30', 'Silvia Herrera', 'Microbióloga', 'Microbiología', NULL, false, NULL, false),
(2, 'B31', 'Patricia Flores', 'Epidemióloga', 'Epidemiología', NULL, false, NULL, false),
(2, 'B32', 'Carolina Cabrera', 'Nutricionista', 'Nutrición', NULL, false, NULL, false),
(2, 'B33', 'Mónica Medina', 'Fisioterapeuta', 'Fisioterapia', NULL, false, NULL, false),
(2, 'B34', 'Marta Escobar', 'Podóloga', 'Podología', NULL, false, NULL, false),
(2, 'B35', 'Lorena Campos', 'Técnica de Laboratorio', 'Laboratorio', NULL, false, NULL, false),
(2, 'B36', 'Vanessa Reyes', 'Enfermera', 'Urgencias', NULL, false, NULL, false),
(2, 'B37', 'Raquel Soto', 'Técnica de Mantenimiento', 'Mantenimiento', '600123456', true, NULL, false),
(2, 'B38', 'Pilar Núñez', 'Técnica de Limpieza', 'Limpieza', '600654321', true, NULL, false),
(2, 'B39', 'Elisa Díaz', 'Seguridad', 'Seguridad', '600987654', true, NULL, false),
(2, 'B40', 'Mercedes Ruiz', 'Jardinera', 'Jardinería', '600456789', true, NULL, false),
(2, 'B41', 'Teresa Ortega', 'Técnica de Ascensores', 'Mantenimiento', '600321987', true, NULL, false),
(2, 'B42', 'María Ramos', 'Técnica de Climatización', 'Mantenimiento', '600654789', true, NULL, false),
(2, 'B43', 'Carmen Morales', 'Electricista', 'Mantenimiento', '600321654', true, NULL, false),
(2, 'B44', 'Beatriz Martín', 'Plomera', 'Mantenimiento', '600987321', true, NULL, false),
(2, 'B45', 'Rosa Navarro', 'Carpintera', 'Mantenimiento', '600654987', true, NULL, false),
(2, 'B46', 'Ana Santos', 'Pintora', 'Mantenimiento', '600123789', true, NULL, false),
(2, 'B47', 'Laura Lozano', 'Conserje', 'Conserjería', '600456321', true, NULL, false),
(2, 'B48', 'Susana Iglesias', 'Portera', 'Portería', '600789123', true, NULL, false),
(2, 'B49', 'Paz Prieto', 'Ayudante de Cocina', 'Cocina', '600321123', true, NULL, false),
(2, 'B50', 'Diana Blanco', 'Técnica de Fontanería', 'Fontanería', '600654123', true, NULL, false);


-- Inserts para el vestuario C (Masculino)
INSERT INTO taquillas (vestuario_id, codigo_taquilla, nombre_apellidos, categoria_profesional, servicio, telefono, empresa_externa, fecha_revision, revisado) VALUES
(3, 'C01', 'Carlos López', 'Auxiliar de Enfermería', 'Enfermería', NULL, false, NULL, false),
(3, 'C02', 'Miguel Rodríguez', 'Médico Especialista', 'Urgencias', NULL, false, NULL, false),
(3, 'C03', 'Pedro Martínez', 'Cirujano', 'Cirugía', NULL, false, NULL, false),
(3, 'C04', 'Juan Sánchez', 'Técnico de Radiología', 'Radiología', NULL, false, NULL, false),
(3, 'C05', 'Luis Hernández', 'Farmacéutico', 'Farmacia', NULL, false, NULL, false),
(3, 'C06', 'José García', 'Anestesista', 'Anestesiología', NULL, false, NULL, false),
(3, 'C07', 'David Jiménez', 'Médico General', 'Medicina General', NULL, false, NULL, false),
(3, 'C08', 'Javier Ruiz', 'Enfermero', 'Enfermería', NULL, false, NULL, false),
(3, 'C09', 'Fernando Ramírez', 'Cardiólogo', 'Cardiología', NULL, false, NULL, false),
(3, 'C10', 'Ricardo Morales', 'Neurólogo', 'Neurología', NULL, false, NULL, false),
(3, 'C11', 'Ángel Díaz', 'Psiquiatra', 'Psiquiatría', NULL, false, NULL, false),
(3, 'C12', 'Eduardo Romero', 'Geriatra', 'Geriatría', NULL, false, NULL, false),
(3, 'C13', 'Vicente Gil', 'Dermatólogo', 'Dermatología', NULL, false, NULL, false),
(3, 'C14', 'Adrián Ortiz', 'Gastroenterólogo', 'Gastroenterología', NULL, false, NULL, false),
(3, 'C15', 'Sergio Torres', 'Nefrólogo', 'Nefrología', NULL, false, NULL, false),
(3, 'C16', 'Pablo Domínguez', 'Neumólogo', 'Neumología', NULL, false, NULL, false),
(3, 'C17', 'Rafael Delgado', 'Oncólogo', 'Oncología', NULL, false, NULL, false),
(3, 'C18', 'Daniel Castillo', 'Oftalmólogo', 'Oftalmología', NULL, false, NULL, false),
(3, 'C19', 'Mario Rivas', 'Otorrinolaringólogo', 'Otorrinolaringología', NULL, false, NULL, false),
(3, 'C20', 'Iván Vázquez', 'Traumatólogo', 'Traumatología', NULL, false, NULL, false),
(3, 'C21', 'Raúl Soto', 'Urólogo', 'Urología', NULL, false, NULL, false),
(3, 'C22', 'Gonzalo Guerrero', 'Endocrinólogo', 'Endocrinología', NULL, false, NULL, false),
(3, 'C23', 'Alberto Moya', 'Hematólogo', 'Hematología', NULL, false, NULL, false),
(3, 'C24', 'Diego Peña', 'Reumatólogo', 'Reumatología', NULL, false, NULL, false),
(3, 'C25', 'Francisco Pardo', 'Rehabilitador', 'Rehabilitación', NULL, false, NULL, false),
(3, 'C26', 'Alejandro León', 'Médico Internista', 'Medicina Interna', NULL, false, NULL, false),
(3, 'C27', 'Marcos Muñoz', 'Ginecólogo', 'Ginecología', NULL, false, NULL, false),
(3, 'C28', 'Héctor Mendoza', 'Pediatra', 'Pediatría', NULL, false, NULL, false),
(3, 'C29', 'Rodrigo Herrera', 'Inmunólogo', 'Inmunología', NULL, false, NULL, false),
(3, 'C30', 'Gabriel Flores', 'Microbiólogo', 'Microbiología', NULL, false, NULL, false),
(3, 'C31', 'Samuel Cabrera', 'Epidemiólogo', 'Epidemiología', NULL, false, NULL, false),
(3, 'C32', 'Rubén Medina', 'Nutricionista', 'Nutrición', NULL, false, NULL, false),
(3, 'C33', 'Manuel Escobar', 'Fisioterapeuta', 'Fisioterapia', NULL, false, NULL, false),
(3, 'C34', 'Hugo Campos', 'Podólogo', 'Podología', NULL, false, NULL, false),
(3, 'C35', 'Víctor Reyes', 'Técnico de Laboratorio', 'Laboratorio', NULL, false, NULL, false),
(3, 'C36', 'Adrián Soto', 'Enfermero', 'Urgencias', NULL, false, NULL, false),
(3, 'C37', 'Andrés Núñez', 'Técnico de Mantenimiento', 'Mantenimiento', '600123456', true, NULL, false),
(3, 'C38', 'Álvaro Díaz', 'Técnico de Limpieza', 'Limpieza', '600654321', true, NULL, false),
(3, 'C39', 'Julio Martín', 'Seguridad', 'Seguridad', '600987654', true, NULL, false),
(3, 'C40', 'Oscar Ramos', 'Jardinero', 'Jardinería', '600456789', true, NULL, false),
(3, 'C41', 'Antonio Morales', 'Técnico de Ascensores', 'Mantenimiento', '600321987', true, NULL, false),
(3, 'C42', 'Félix García', 'Técnico de Climatización', 'Mantenimiento', '600654789', true, NULL, false),
(3, 'C43', 'Marcelo Sánchez', 'Electricista', 'Mantenimiento', '600321654', true, NULL, false),
(3, 'C44', 'Roberto Ruiz', 'Plomero', 'Mantenimiento', '600987321', true, NULL, false),
(3, 'C45', 'Tomás Navarro', 'Carpintero', 'Mantenimiento', '600654987', true, NULL, false),
(3, 'C46', 'Cristian Santos', 'Pintor', 'Mantenimiento', '600123789', true, NULL, false),
(3, 'C47', 'Ramón Lozano', 'Conserje', 'Conserjería', '600456321', true, NULL, false),
(3, 'C48', 'Felipe Iglesias', 'Portero', 'Portería', '600789123', true, NULL, false),
(3, 'C49', 'Hernán Prieto', 'Ayudante de Cocina', 'Cocina', '600321123', true, NULL, false),
(3, 'C50', 'Esteban Blanco', 'Técnico de Fontanería', 'Fontanería', '600654123', true, NULL, false);


-- Inserts para el vestuario D (Femenino)
INSERT INTO taquillas (vestuario_id, codigo_taquilla, nombre_apellidos, categoria_profesional, servicio, telefono, empresa_externa, fecha_revision, revisado) VALUES
(4, 'D01', 'Alicia Gómez', 'Auxiliar de Enfermería', 'Enfermería', NULL, false, NULL, false),
(4, 'D02', 'Blanca López', 'Médico Especialista', 'Urgencias', NULL, false, NULL, false),
(4, 'D03', 'Clara Martínez', 'Cirujana', 'Cirugía', NULL, false, NULL, false),
(4, 'D04', 'Daniela Rodríguez', 'Técnica de Radiología', 'Radiología', NULL, false, NULL, false),
(4, 'D05', 'Elena Hernández', 'Farmacéutica', 'Farmacia', NULL, false, NULL, false),
(4, 'D06', 'Fernanda Sánchez', 'Anestesista', 'Anestesiología', NULL, false, NULL, false),
(4, 'D07', 'Gabriela García', 'Médica General', 'Medicina General', NULL, false, NULL, false),
(4, 'D08', 'Hilda Jiménez', 'Enfermera', 'Enfermería', NULL, false, NULL, false),
(4, 'D09', 'Inés Ramírez', 'Cardióloga', 'Cardiología', NULL, false, NULL, false),
(4, 'D10', 'Juana Morales', 'Neuróloga', 'Neurología', NULL, false, NULL, false),
(4, 'D11', 'Karla Ruiz', 'Psiquiatra', 'Psiquiatría', NULL, false, NULL, false),
(4, 'D12', 'Laura Romero', 'Geriatra', 'Geriatría', NULL, false, NULL, false),
(4, 'D13', 'Marta Gil', 'Dermatóloga', 'Dermatología', NULL, false, NULL, false),
(4, 'D14', 'Natalia Ortiz', 'Gastroenteróloga', 'Gastroenterología', NULL, false, NULL, false),
(4, 'D15', 'Olga Torres', 'Nefróloga', 'Nefrología', NULL, false, NULL, false),
(4, 'D16', 'Patricia Domínguez', 'Neumóloga', 'Neumología', NULL, false, NULL, false),
(4, 'D17', 'Raquel Delgado', 'Oncóloga', 'Oncología', NULL, false, NULL, false),
(4, 'D18', 'Sara Castillo', 'Oftalmóloga', 'Oftalmología', NULL, false, NULL, false),
(4, 'D19', 'Teresa Rivas', 'Otorrinolaringóloga', 'Otorrinolaringología', NULL, false, NULL, false),
(4, 'D20', 'Ursula Vázquez', 'Traumatóloga', 'Traumatología', NULL, false, NULL, false),
(4, 'D21', 'Verónica Soto', 'Uróloga', 'Urología', NULL, false, NULL, false),
(4, 'D22', 'Wendy Guerrero', 'Endocrinóloga', 'Endocrinología', NULL, false, NULL, false),
(4, 'D23', 'Ximena Moya', 'Hematóloga', 'Hematología', NULL, false, NULL, false),
(4, 'D24', 'Yolanda Peña', 'Reumatóloga', 'Reumatología', NULL, false, NULL, false),
(4, 'D25', 'Zaira Pardo', 'Rehabilitadora', 'Rehabilitación', NULL, false, NULL, false),
(4, 'D26', 'Adela León', 'Médica Internista', 'Medicina Interna', NULL, false, NULL, false),
(4, 'D27', 'Beatriz Muñoz', 'Ginecóloga', 'Ginecología', NULL, false, NULL, false),
(4, 'D28', 'Claudia Mendoza', 'Pediatra', 'Pediatría', NULL, false, NULL, false),
(4, 'D29', 'Dolores Herrera', 'Inmunóloga', 'Inmunología', NULL, false, NULL, false),
(4, 'D30', 'Eva Flores', 'Microbióloga', 'Microbiología', NULL, false, NULL, false),
(4, 'D31', 'Fátima Cabrera', 'Epidemióloga', 'Epidemiología', NULL, false, NULL, false),
(4, 'D32', 'Gloria Medina', 'Nutricionista', 'Nutrición', NULL, false, NULL, false),
(4, 'D33', 'Hilda Escobar', 'Fisioterapeuta', 'Fisioterapia', NULL, false, NULL, false),
(4, 'D34', 'Irene Campos', 'Podóloga', 'Podología', NULL, false, NULL, false),
(4, 'D35', 'Jessica Reyes', 'Técnica de Laboratorio', 'Laboratorio', NULL, false, NULL, false),
(4, 'D36', 'Karen Soto', 'Enfermera', 'Urgencias', NULL, false, NULL, false),
(4, 'D37', 'Liliana Núñez', 'Técnica de Mantenimiento', 'Mantenimiento', '600123456', true, NULL, false),
(4, 'D38', 'Marina Díaz', 'Técnica de Limpieza', 'Limpieza', '600654321', true, NULL, false),
(4, 'D39', 'Nadia Martín', 'Seguridad', 'Seguridad', '600987654', true, NULL, false),
(4, 'D40', 'Olga Ramos', 'Jardinera', 'Jardinería', '600456789', true, NULL, false),
(4, 'D41', 'Paula Morales', 'Técnica de Ascensores', 'Mantenimiento', '600321987', true, NULL, false),
(4, 'D42', 'Rocío García', 'Técnica de Climatización', 'Mantenimiento', '600654789', true, NULL, false),
(4, 'D43', 'Sonia Sánchez', 'Electricista', 'Mantenimiento', '600321654', true, NULL, false),
(4, 'D44', 'Tatiana Ruiz', 'Plomera', 'Mantenimiento', '600987321', true, NULL, false),
(4, 'D45', 'Ursula Navarro', 'Carpintera', 'Mantenimiento', '600654987', true, NULL, false),
(4, 'D46', 'Verónica Santos', 'Pintora', 'Mantenimiento', '600123789', true, NULL, false),
(4, 'D47', 'Wendy Lozano', 'Conserje', 'Conserjería', '600456321', true, NULL, false),
(4, 'D48', 'Ximena Iglesias', 'Portera', 'Portería', '600789123', true, NULL, false),
(4, 'D49', 'Yolanda Prieto', 'Ayudante de Cocina', 'Cocina', '600321123', true, NULL, false),
(4, 'D50', 'Zaira Blanco', 'Técnica de Fontanería', 'Fontanería', '600654123', true, NULL, false);

-- Inserts para el vestuario E (Vestuario_id = 5)
INSERT INTO taquillas (vestuario_id, codigo_taquilla, nombre_apellidos, categoria_profesional, servicio, telefono, empresa_externa, fecha_revision, revisado) VALUES
(5, 'E01', 'Carlos Pérez', 'Auxiliar de Enfermería', 'Enfermería', NULL, false, NULL, false),
(5, 'E02', 'Laura Gómez', 'Médico Especialista', 'Urgencias', NULL, false, NULL, false),
(5, 'E03', 'Ana Rodríguez', 'Cirujana', 'Cirugía', NULL, false, NULL, false),
(5, 'E04', 'Juan Martínez', 'Técnico de Radiología', 'Radiología', NULL, false, NULL, false),
(5, 'E05', 'Marta Sánchez', 'Farmacéutica', 'Farmacia', NULL, false, NULL, false),
(5, 'E06', 'Pedro Hernández', 'Anestesista', 'Anestesiología', NULL, false, NULL, false),
(5, 'E07', 'Luis García', 'Médico General', 'Medicina General', NULL, false, NULL, false),
(5, 'E08', 'Isabel Jiménez', 'Enfermera', 'Enfermería', NULL, false, NULL, false),
(5, 'E09', 'David Ramírez', 'Cardiólogo', 'Cardiología', NULL, false, NULL, false),
(5, 'E10', 'Cristina Morales', 'Neuróloga', 'Neurología', NULL, false, NULL, false),
(5, 'E11', 'Rosa Ruiz', 'Psiquiatra', 'Psiquiatría', NULL, false, NULL, false),
(5, 'E12', 'Mario Romero', 'Geriatra', 'Geriatría', NULL, false, NULL, false),
(5, 'E13', 'Adriana Gil', 'Dermatóloga', 'Dermatología', NULL, false, NULL, false),
(5, 'E14', 'Francisco Ortiz', 'Gastroenterólogo', 'Gastroenterología', NULL, false, NULL, false),
(5, 'E15', 'Daniel Torres', 'Nefrólogo', 'Nefrología', NULL, false, NULL, false),
(5, 'E16', 'Carolina Domínguez', 'Neumóloga', 'Neumología', NULL, false, NULL, false),
(5, 'E17', 'Alberto Delgado', 'Oncólogo', 'Oncología', NULL, false, NULL, false),
(5, 'E18', 'Lucía Castillo', 'Oftalmóloga', 'Oftalmología', NULL, false, NULL, false),
(5, 'E19', 'Héctor Rivas', 'Otorrinolaringólogo', 'Otorrinolaringología', NULL, false, NULL, false),
(5, 'E20', 'Claudia Vázquez', 'Traumatóloga', 'Traumatología', NULL, false, NULL, false),
(5, 'E21', 'Raquel Soto', 'Uróloga', 'Urología', NULL, false, NULL, false),
(5, 'E22', 'Gabriel Guerrero', 'Endocrinólogo', 'Endocrinología', NULL, false, NULL, false),
(5, 'E23', 'Victoria Moya', 'Hematóloga', 'Hematología', NULL, false, NULL, false),
(5, 'E24', 'Esteban Peña', 'Reumatólogo', 'Reumatología', NULL, false, NULL, false),
(5, 'E25', 'Felipe Pardo', 'Rehabilitador', 'Rehabilitación', NULL, false, NULL, false),
(5, 'E26', 'Carmen León', 'Médica Internista', 'Medicina Interna', NULL, false, NULL, false),
(5, 'E27', 'Rodrigo Muñoz', 'Ginecólogo', 'Ginecología', NULL, false, NULL, false),
(5, 'E28', 'Gloria Mendoza', 'Pediatra', 'Pediatría', NULL, false, NULL, false),
(5, 'E29', 'Silvia Herrera', 'Inmunóloga', 'Inmunología', NULL, false, NULL, false),
(5, 'E30', 'Alfredo Flores', 'Microbiólogo', 'Microbiología', NULL, false, NULL, false),
(5, 'E31', 'Teresa Cabrera', 'Epidemióloga', 'Epidemiología', NULL, false, NULL, false),
(5, 'E32', 'Manuel Medina', 'Nutricionista', 'Nutrición', NULL, false, NULL, false),
(5, 'E33', 'Lorena Escobar', 'Fisioterapeuta', 'Fisioterapia', NULL, false, NULL, false),
(5, 'E34', 'Carlos Campos', 'Podólogo', 'Podología', NULL, false, NULL, false),
(5, 'E35', 'Alicia Reyes', 'Técnica de Laboratorio', 'Laboratorio', NULL, false, NULL, false),
(5, 'E36', 'Ricardo Soto', 'Enfermero', 'Urgencias', NULL, false, NULL, false),
(5, 'E37', 'Hugo Núñez', 'Técnico de Mantenimiento', 'Mantenimiento', '600123456', true, NULL, false),
(5, 'E38', 'Sergio Díaz', 'Técnico de Limpieza', 'Limpieza', '600654321', true, NULL, false),
(5, 'E39', 'Mario Martín', 'Seguridad', 'Seguridad', '600987654', true, NULL, false),
(5, 'E40', 'Fernando Ramos', 'Jardinero', 'Jardinería', '600456789', true, NULL, false),
(5, 'E41', 'Elena Morales', 'Técnica de Ascensores', 'Mantenimiento', '600321987', true, NULL, false),
(5, 'E42', 'Alba García', 'Técnica de Climatización', 'Mantenimiento', '600654789', true, NULL, false),
(5, 'E43', 'Nicolás Sánchez', 'Electricista', 'Mantenimiento', '600321654', true, NULL, false),
(5, 'E44', 'Lucas Ruiz', 'Plomero', 'Mantenimiento', '600987321', true, NULL, false),
(5, 'E45', 'Iván Navarro', 'Carpintero', 'Mantenimiento', '600654987', true, NULL, false),
(5, 'E46', 'Ángel Santos', 'Pintor', 'Mantenimiento', '600123789', true, NULL, false),
(5, 'E47', 'Mateo Lozano', 'Conserje', 'Conserjería', '600456321', true, NULL, false),
(5, 'E48', 'Claudia Iglesias', 'Portera', 'Portería', '600789123', true, NULL, false),
(5, 'E49', 'Ángela Prieto', 'Ayudante de Cocina', 'Cocina', '600321123', true, NULL, false),
(5, 'E50', 'Andrés Blanco', 'Técnico de Fontanería', 'Fontanería', '600654123', true, NULL, false);

-- Inserts para el vestuario F (Vestuario_id = 6)
INSERT INTO taquillas (vestuario_id, codigo_taquilla, nombre_apellidos, categoria_profesional, servicio, telefono, empresa_externa, fecha_revision, revisado) VALUES
(6, 'F01', 'María Pérez', 'Auxiliar de Enfermería', 'Enfermería', NULL, false, NULL, false),
(6, 'F02', 'José López', 'Médico Especialista', 'Urgencias', NULL, false, NULL, false),
(6, 'F03', 'Lucía Rodríguez', 'Cirujana', 'Cirugía', NULL, false, NULL, false),
(6, 'F04', 'Alberto Martínez', 'Técnico de Radiología', 'Radiología', NULL, false, NULL, false),
(6, 'F05', 'Elisa Hernández', 'Farmacéutica', 'Farmacia', NULL, false, NULL, false),
(6, 'F06', 'Miguel Sánchez', 'Anestesista', 'Anestesiología', NULL, false, NULL, false),
(6, 'F07', 'Carmen García', 'Médica General', 'Medicina General', NULL, false, NULL, false),
(6, 'F08', 'Juan Jiménez', 'Enfermero', 'Enfermería', NULL, false, NULL, false),
(6, 'F09', 'Sonia Ramírez', 'Cardióloga', 'Cardiología', NULL, false, NULL, false),
(6, 'F10', 'Carlos Morales', 'Neurólogo', 'Neurología', NULL, false, NULL, false),
(6, 'F11', 'Nuria Ruiz', 'Psiquiatra', 'Psiquiatría', NULL, false, NULL, false),
(6, 'F12', 'Víctor Romero', 'Geriatra', 'Geriatría', NULL, false, NULL, false),
(6, 'F13', 'Isabel Gil', 'Dermatóloga', 'Dermatología', NULL, false, NULL, false),
(6, 'F14', 'Andrés Ortiz', 'Gastroenterólogo', 'Gastroenterología', NULL, false, NULL, false),
(6, 'F15', 'Sandra Torres', 'Nefróloga', 'Nefrología', NULL, false, NULL, false),
(6, 'F16', 'Pedro Domínguez', 'Neumólogo', 'Neumología', NULL, false, NULL, false),
(6, 'F17', 'Mónica Delgado', 'Oncóloga', 'Oncología', NULL, false, NULL, false),
(6, 'F18', 'David Castillo', 'Oftalmólogo', 'Oftalmología', NULL, false, NULL, false),
(6, 'F19', 'Clara Rivas', 'Otorrinolaringóloga', 'Otorrinolaringología', NULL, false, NULL, false),
(6, 'F20', 'Antonio Vázquez', 'Traumatólogo', 'Traumatología', NULL, false, NULL, false),
(6, 'F21', 'Lorena Soto', 'Uróloga', 'Urología', NULL, false, NULL, false),
(6, 'F22', 'Francisco Guerrero', 'Endocrinólogo', 'Endocrinología', NULL, false, NULL, false),
(6, 'F23', 'Cristina Moya', 'Hematóloga', 'Hematología', NULL, false, NULL, false),
(6, 'F24', 'Diego Peña', 'Reumatólogo', 'Reumatología', NULL, false, NULL, false),
(6, 'F25', 'Gabriel Pardo', 'Rehabilitador', 'Rehabilitación', NULL, false, NULL, false),
(6, 'F26', 'Silvia León', 'Médica Internista', 'Medicina Interna', NULL, false, NULL, false),
(6, 'F27', 'Javier Muñoz', 'Ginecólogo', 'Ginecología', NULL, false, NULL, false),
(6, 'F28', 'Patricia Mendoza', 'Pediatra', 'Pediatría', NULL, false, NULL, false),
(6, 'F29', 'Raúl Herrera', 'Inmunólogo', 'Inmunología', NULL, false, NULL, false),
(6, 'F30', 'Teresa Flores', 'Microbióloga', 'Microbiología', NULL, false, NULL, false),
(6, 'F31', 'José Cabrera', 'Epidemiólogo', 'Epidemiología', NULL, false, NULL, false),
(6, 'F32', 'Marina Medina', 'Nutricionista', 'Nutrición', NULL, false, NULL, false),
(6, 'F33', 'Ricardo Escobar', 'Fisioterapeuta', 'Fisioterapia', NULL, false, NULL, false),
(6, 'F34', 'Luisa Campos', 'Podóloga', 'Podología', NULL, false, NULL, false),
(6, 'F35', 'Fernando Reyes', 'Técnico de Laboratorio', 'Laboratorio', NULL, false, NULL, false),
(6, 'F36', 'Gonzalo Soto', 'Enfermero', 'Urgencias', NULL, false, NULL, false),
(6, 'F37', 'Natalia Núñez', 'Técnica de Mantenimiento', 'Mantenimiento', '600123456', true, NULL, false),
(6, 'F38', 'Sofía Díaz', 'Técnica de Limpieza', 'Limpieza', '600654321', true, NULL, false),
(6, 'F39', 'Julio Martín', 'Seguridad', 'Seguridad', '600987654', true, NULL, false),
(6, 'F40', 'Laura Ramos', 'Jardinera', 'Jardinería', '600456789', true, NULL, false),
(6, 'F41', 'Jorge Morales', 'Técnico de Ascensores', 'Mantenimiento', '600321987', true, NULL, false),
(6, 'F42', 'Carlos García', 'Técnico de Climatización', 'Mantenimiento', '600654789', true, NULL, false),
(6, 'F43', 'Alejandro Sánchez', 'Electricista', 'Mantenimiento', '600321654', true, NULL, false),
(6, 'F44', 'Rosa Ruiz', 'Plomera', 'Mantenimiento', '600987321', true, NULL, false),
(6, 'F45', 'Daniel Navarro', 'Carpintero', 'Mantenimiento', '600654987', true, NULL, false),
(6, 'F46', 'Héctor Santos', 'Pintor', 'Mantenimiento', '600123789', true, NULL, false),
(6, 'F47', 'Marta Lozano', 'Conserje', 'Conserjería', '600456321', true, NULL, false),
(6, 'F48', 'Laura Iglesias', 'Portera', 'Portería', '600789123', true, NULL, false),
(6, 'F49', 'Ángel Prieto', 'Ayudante de Cocina', 'Cocina', '600321123', true, NULL, false),
(6, 'F50', 'Elena Blanco', 'Técnica de Fontanería', 'Fontanería', '600654123', true, NULL, false);

INSERT INTO taquillas (vestuario_id, codigo_taquilla, nombre_apellidos, categoria_profesional, servicio, telefono, empresa_externa, fecha_revision, revisado) VALUES
(7, 'G01', 'Nombre Apellido 1', 'Categoría Profesional 1', 'Servicio 1', '600000001', false, NULL, false),
(7, 'G02', 'Nombre Apellido 2', 'Categoría Profesional 2', 'Servicio 2', '600000002', false, NULL, false),
(7, 'G03', 'Nombre Apellido 3', 'Categoría Profesional 3', 'Servicio 3', '600000003', false, NULL, false),
(7, 'G04', 'Nombre Apellido 4', 'Categoría Profesional 4', 'Servicio 4', '600000004', false, NULL, false),
(7, 'G05', 'Nombre Apellido 5', 'Categoría Profesional 5', 'Servicio 5', '600000005', false, NULL, false),
(7, 'G06', 'Nombre Apellido 6', 'Categoría Profesional 6', 'Servicio 6', '600000006', false, NULL, false),
(7, 'G07', 'Nombre Apellido 7', 'Categoría Profesional 7', 'Servicio 7', '600000007', false, NULL, false),
(7, 'G08', 'Nombre Apellido 8', 'Categoría Profesional 8', 'Servicio 8', '600000008', false, NULL, false),
(7, 'G09', 'Nombre Apellido 9', 'Categoría Profesional 9', 'Servicio 9', '600000009', false, NULL, false),
(7, 'G10', 'Nombre Apellido 10', 'Categoría Profesional 10', 'Servicio 10', '600000010', false, NULL, false),
(7, 'G11', 'Nombre Apellido 11', 'Categoría Profesional 11', 'Servicio 11', '600000011', false, NULL, false),
(7, 'G12', 'Nombre Apellido 12', 'Categoría Profesional 12', 'Servicio 12', '600000012', false, NULL, false),
(7, 'G13', 'Nombre Apellido 13', 'Categoría Profesional 13', 'Servicio 13', '600000013', false, NULL, false),
(7, 'G14', 'Nombre Apellido 14', 'Categoría Profesional 14', 'Servicio 14', '600000014', false, NULL, false),
(7, 'G15', 'Nombre Apellido 15', 'Categoría Profesional 15', 'Servicio 15', '600000015', false, NULL, false),
(7, 'G16', 'Nombre Apellido 16', 'Categoría Profesional 16', 'Servicio 16', '600000016', false, NULL, false),
(7, 'G17', 'Nombre Apellido 17', 'Categoría Profesional 17', 'Servicio 17', '600000017', false, NULL, false),
(7, 'G18', 'Nombre Apellido 18', 'Categoría Profesional 18', 'Servicio 18', '600000018', false, NULL, false),
(7, 'G19', 'Nombre Apellido 19', 'Categoría Profesional 19', 'Servicio 19', '600000019', false, NULL, false),
(7, 'G20', 'Nombre Apellido 20', 'Categoría Profesional 20', 'Servicio 20', '600000020', false, NULL, false),
(7, 'G21', 'Nombre Apellido 21', 'Categoría Profesional 21', 'Servicio 21', '600000021', false, NULL, false),
(7, 'G22', 'Nombre Apellido 22', 'Categoría Profesional 22', 'Servicio 22', '600000022', false, NULL, false),
(7, 'G23', 'Nombre Apellido 23', 'Categoría Profesional 23', 'Servicio 23', '600000023', false, NULL, false),
(7, 'G24', 'Nombre Apellido 24', 'Categoría Profesional 24', 'Servicio 24', '600000024', false, NULL, false),
(7, 'G25', 'Nombre Apellido 25', 'Categoría Profesional 25', 'Servicio 25', '600000025', false, NULL, false),
(7, 'G26', 'Nombre Apellido 26', 'Categoría Profesional 26', 'Servicio 26', '600000026', false, NULL, false),
(7, 'G27', 'Nombre Apellido 27', 'Categoría Profesional 27', 'Servicio 27', '600000027', false, NULL, false),
(7, 'G28', 'Nombre Apellido 28', 'Categoría Profesional 28', 'Servicio 28', '600000028', false, NULL, false),
(7, 'G29', 'Nombre Apellido 29', 'Categoría Profesional 29', 'Servicio 29', '600000029', false, NULL, false),
(7, 'G30', 'Nombre Apellido 30', 'Categoría Profesional 30', 'Servicio 30', '600000030', false, NULL, false);
